[functions]
  external_node_modules = ["ejs","express", "cookie-parser", "body-parser", "bcrypt", "nodemailer", "sqlite3", "util"]
  node_bundler = "esbuild"
  included_files = ["views/**/*"]
  included_files = ["**/healthdata.db"]

[[redirects]]
 from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
