[functions]
  external_node_modules = ["express", "cookie-parser", "body-parser", "bcrypt", "nodemailer", "sqlite3"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
